package com.jj.taobao.model;

import org.springframework.stereotype.Component;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.title
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.gmt_create
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.gmt_modified
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.creator
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.comment_count
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.view_count
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.like_count
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.tag
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.title
     *
     * @return the value of product.title
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.title
     *
     * @param title the value for product.title
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_create
     *
     * @return the value of product.gmt_create
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_create
     *
     * @param gmtCreate the value for product.gmt_create
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_modified
     *
     * @return the value of product.gmt_modified
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_modified
     *
     * @param gmtModified the value for product.gmt_modified
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.creator
     *
     * @return the value of product.creator
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.creator
     *
     * @param creator the value for product.creator
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.comment_count
     *
     * @return the value of product.comment_count
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.comment_count
     *
     * @param commentCount the value for product.comment_count
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.view_count
     *
     * @return the value of product.view_count
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.view_count
     *
     * @param viewCount the value for product.view_count
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.like_count
     *
     * @return the value of product.like_count
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.like_count
     *
     * @param likeCount the value for product.like_count
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.tag
     *
     * @return the value of product.tag
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.tag
     *
     * @param tag the value for product.tag
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbg.generated Fri Apr 22 23:31:52 GMT+08:00 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}