package com.jj.taobao.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.ID
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.TITLE
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.GMT_CREATE
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.GMT_MODIFIED
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CREATOR
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.COMMENT_COUNT
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.VIEW_COUNT
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.LIKE_COUNT
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.TAG
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.FILE_PATH
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.DESCRIPTION
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.ID
     *
     * @return the value of PRODUCT.ID
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.ID
     *
     * @param id the value for PRODUCT.ID
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.TITLE
     *
     * @return the value of PRODUCT.TITLE
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.TITLE
     *
     * @param title the value for PRODUCT.TITLE
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.GMT_CREATE
     *
     * @return the value of PRODUCT.GMT_CREATE
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.GMT_CREATE
     *
     * @param gmtCreate the value for PRODUCT.GMT_CREATE
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.GMT_MODIFIED
     *
     * @return the value of PRODUCT.GMT_MODIFIED
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.GMT_MODIFIED
     *
     * @param gmtModified the value for PRODUCT.GMT_MODIFIED
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CREATOR
     *
     * @return the value of PRODUCT.CREATOR
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CREATOR
     *
     * @param creator the value for PRODUCT.CREATOR
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.COMMENT_COUNT
     *
     * @return the value of PRODUCT.COMMENT_COUNT
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.COMMENT_COUNT
     *
     * @param commentCount the value for PRODUCT.COMMENT_COUNT
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.VIEW_COUNT
     *
     * @return the value of PRODUCT.VIEW_COUNT
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.VIEW_COUNT
     *
     * @param viewCount the value for PRODUCT.VIEW_COUNT
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.LIKE_COUNT
     *
     * @return the value of PRODUCT.LIKE_COUNT
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.LIKE_COUNT
     *
     * @param likeCount the value for PRODUCT.LIKE_COUNT
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.TAG
     *
     * @return the value of PRODUCT.TAG
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.TAG
     *
     * @param tag the value for PRODUCT.TAG
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.FILE_PATH
     *
     * @return the value of PRODUCT.FILE_PATH
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.FILE_PATH
     *
     * @param filePath the value for PRODUCT.FILE_PATH
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.DESCRIPTION
     *
     * @return the value of PRODUCT.DESCRIPTION
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.DESCRIPTION
     *
     * @param description the value for PRODUCT.DESCRIPTION
     *
     * @mbg.generated Tue May 03 20:36:29 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}