CREATE TABLE USER
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACCOUNT_ID   VARCHAR(100),
    USERNAME     VARCHAR(100),
    PASSWORD     VARCHAR(20)                       NOT NULL,
    TOKEN        VARCHAR(36),
    GMT_CREATE   BIGINT,
    GMT_MODIFIED BIGINT,
    AVATAR_URL   VARCHAR(100)                      NULL
);
