CREATE TABLE `PRODUCT`
(
    ID            BIGINT AUTO_INCREMENT,
    TITLE         VARCHAR(50) NULL,
    DESCRIPTION   TEXT NULL,
    GMT_CREATE    BIGINT NULL,
    GMT_MODIFIED  BIGINT NULL,
    CREATOR       BIGINT NULL,
    COMMENT_COUNT INT DEFAULT 0 NULL,
    VIEW_COUNT    INT DEFAULT 0 NULL,
    LIKE_COUNT    INT DEFAULT 0 NULL,
    TAG           VARCHAR(256) NULL,
    FILE_PATH     VARCHAR(256) NULL,
    CONSTRAINT PRODUCT_PK
        PRIMARY KEY (ID)
);
